"""Add semantic memory

Revision ID: b5e2681000a2
Revises: df95b464e9c1
Create Date: 2026-05-20 10:10:37.028349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e2681000a2'
down_revision: Union[str, Sequence[str], None] = 'df95b464e9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semantic_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_memory_category'), 'semantic_memory', ['category'], unique=False)
    op.create_index(op.f('ix_semantic_memory_session_id'), 'semantic_memory', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semantic_memory_session_id'), table_name='semantic_memory')
    op.drop_index(op.f('ix_semantic_memory_category'), table_name='semantic_memory')
    op.drop_table('semantic_memory')
    # ### end Alembic commands ###
